apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ts-keyvault
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${kvsp_aks}
    keyvaultName: ${keyVaultName}
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: "test-tsservice-examplesecret"
          objectType: secret
          objectVersion: ""
        - |
          objectName: "test-tsservice-examplekey"
          objectType: key
          objectVersion: ""
    tenantId: ${tenantId}