apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${kvsp_aks}
  labels:
    azure.workload.identity/use: "true"
  name: ${svc_acct_name}
  namespace: ${svc_acct_namespace}